project_id = "rophutqdblgkasdooxtg"

[functions.create-tenant]
verify_jwt = true

[functions.create-order]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.erp-connect]
verify_jwt = true

[functions.erp-field-mapping-ai]
verify_jwt = true

[functions.erp-sync]
verify_jwt = true

[functions.erp-refresh-token]
verify_jwt = true

[functions.erp-webhook]
verify_jwt = false
